---
abstract: 'Common rules for searching for DICOM things.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Find-Rule-Dicom
no_index:
  directory:
    - inc
    - t
requires:
  Dicom::File::Detect: 0.01
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=File-Find-Rule-Dicom
  homepage: https://github.com/tupinek/File-Find-Rule-Dicom
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: git://github.com/tupinek/File-Find-Rule-Dicom
version: 0.01
